export default {
    lesson_category: "api-course/category",
    lesson_main: "api-main/",
    lesson_list: "api-course/list",
    lesson_detail: "api-course/detail",
    lesson_fav: "api-course/fav",
    lesson_lesson: "api-course/lesson",
    lesson_forbuy: "api-course/forbuy",
    lesson_pay: "api-course/pay",
    lesson_lessonDetail: "api-course/lessonDetail",
    lesson_like: "api-course/like",
    lesson_text: "api-course/text",
    lesson_note: "api-course/note",
    lesson_comment: "api-course/comment",
    lesson_commentList: "api-course/commentList",
    lesson_question: "api-course/question",
    lesson_search: "api-course/search",
    lesson_answer: "api-course/answer",
    lesson_result: "api-course/result",
    lesson_playTime: "api-course/playtime"
}