export default {
    member_my: "api-user-main/my",
    member_faq: "api-user-main/faq",
    member_feedback: "api-user-main/feedback",
    member_msg: "api-user-main/msg",
    member_msgDetail: "api-user-main/msgDetail",
    member_check: "api-user-main/check",
    member_fav: "api-user-main/fav",
    member_read: "api-user-main/read",
    member_course: "api-user-study/course",
    member_courseDetail: "api-user-study/courseDetail",
    member_forday: "api-user-study/forday",
    member_saveday: "api-user-study/saveday",
    member_forSchedule: "api-user-study/forSchedule",
    member_saveSchedule: "api-user-study/saveSchedule",
    member_error: "api-user-main/error",
    member_add: "api-user-card/add",
    member_update: "api-user-main/update",
    member_upload: "api-upload/face",
    member_user: "api-user-card/user"
}